@TOKEN=TOKEN_KEY
### LOGIN
POST http://localhost:3000/login
content-type: application/json

{
    "email": "teste@teste.br",
    "password": "teste01"
}

### ONGs
GET http://localhost:3000/ong

### CREATE
POST http://localhost:3000/660/ong
content-type: application/json
Authorization: : Bearer {{TOKEN}}

{
        "id": 1,
        "name": "Teste",
        "logadouro": "rua teste",
        "numero": 1,
        "cidade": "teste",
        "cep": 11222999,
        "descricao": "Cantinho do Doguinho"
}

### UPDATE
PUT http://localhost:3000/660/ong/1
Authorization: : Bearer {{TOKEN}}

content-type: application/json

{
        "id": 1,
        "name": "Teste",
        "logadouro": "rua teste",
        "numero": 1,
        "cidade": "teste",
        "cep": 11222999,
        "descricao": "Cantinho do Doguinho"
}

### DELETE ONG
DELETE http://localhost:3000/660/ong/1
Authorization: : Bearer {{TOKEN}}
