### USERS
GET http://localhost:3000/users

### REGISTRO
POST http://localhost:3000/register
content-type: application/json

{
    "email": "teste@teste.br",
    "password": "teste01",
}

### LOGIN
POST http://localhost:3000/login
content-type: application/json

{
    "email": "teste@teste.br",
    "password": "teste01"
}