### ONGs
GET http://localhost:3000/atividades

### CREATE
POST http://localhost:3000/atividades
content-type: application/json

{
        "id": 1,
        "nome": "Atividade Teste",
        "data": "01/01/2022",
        "nvoluntarios": 1
}

### UPDATE
PUT http://localhost:3000/atividades/1

content-type: application/json

{
        "id": 1,
        "nome": "Atividade Teste",
        "data": "01/01/2022",
        "nvoluntarios": 1
}

### DELETE ONG
DELETE http://localhost:3000/atividades/1